### ISSUE TITLE
ManiaPlanet doesnt unload cached script !

### ISSUE THREAD

**Issue by BestNoob** [maniaplanet/maniascript-reference#1]
I tryed to load an old script (PlatformMulti.Script.txt) from 2013 by using "local network - create server"
and now every time i try to load this script it displays the same error message and code again and again doesnt matter what i change via notpead in the file. 

I can delete the whole code inside this file, ManiaPlanet always load the cached stuff ....

(and yes i completly quitted ManiaPlanet in between)

**Comment by magnetik** [comment]
This is not the place for questions and support.

You should ask your question on the forum.
